---
- name: Check latest helm-docs version
  ansible.builtin.uri:
    url: https://api.github.com/repos/norwoodj/helm-docs/releases/latest
    return_content: true
    user: "{{ github_user }}"
    password: "{{ github_token }}"
    force_basic_auth: "{{ gh_auth }}"
  register: helm_docs_github_details
  when: helm_docs.version is undefined
  tags:
    - never
    - helm
    - helm-docs
    - work

- name: Set helm_docs.version
  ansible.builtin.set_fact:
    helm_docs:
      version: "{{ helm_docs_github_details.json.tag_name }}"
  when: not helm_docs_github_details is skipped
  tags:
    - never
    - helm
    - helm-docs
    - work

- name: Install helm-docs
  ansible.builtin.unarchive:
    src: "https://github.com/norwoodj/helm-docs/releases/download/{{ helm_docs.version }}/helm-docs_{{ helm_docs.version | replace ('v', '') }}_Linux_x86_64.tar.gz"
    dest: "{{ ansible_env.HOME }}/.local/bin"
    remote_src: true
    include:
      - helm-docs
  tags:
    - never
    - helm
    - helm-docs
    - work
