---
- name: Check latest helm version
  ansible.builtin.uri:
    url: https://api.github.com/repos/helm/helm/releases/latest
    return_content: true
    user: "{{ github_user }}"
    password: "{{ github_token }}"
    force_basic_auth: "{{ gh_auth }}"
  register: helm_github_details
  when: helm.version is undefined
  tags:
    - never
    - helm
    - work

- name: Set helm.version
  ansible.builtin.set_fact:
    helm:
      version: "{{ helm_github_details.json.tag_name }}"
  when: not helm_github_details is skipped
  tags:
    - never
    - helm
    - work

- name: Install helm
  ansible.builtin.unarchive:
    src: "https://get.helm.sh/helm-{{ helm.version }}-linux-amd64.tar.gz"
    dest: "{{ ansible_env.HOME }}/.local/bin"
    remote_src: true
    extra_opts:
      - '--strip-components=1'
    include:
      - 'linux-amd64/helm'
  register: helm_install
  tags:
    - never
    - helm
    - work

- name: Generate bash completions
  ansible.builtin.shell:
    cmd: helm completion bash > "{{ ansible_env.HOME }}/.local/share/bash-completion/completions/helm"
  when: helm_install is changed
  tags:
    - never
    - helm
    - work

- name: Install helm plugins
  ansible.builtin.shell: 
    cmd: helm plugin install {{ item }}
    creates: "{{ ansible_env.HOME }}/.local/share/helm/plugins/{{ item | basename }}"
  loop: "{{ helm_plugins }}"
  tags:
    - never
    - helm
    - helm-plugins
    - work

- name: Update helm plugins
  ansible.builtin.shell: 
    cmd: helm plugin update {{ item | basename | replace ('helm-', '') }}
  loop: "{{ helm_plugins }}"
  tags:
    - never
    - helm
    - helm-plugins
    - work
