---
- name: Remove local python tools installed by pip
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: "/usr/bin/pip3"
    extra_args: "--break-system-packages"
    state: absent
  loop: "{{ python_tools }}"
  tags:
    - never
    - py
    - tools
