---
- name: Bootstrap local env
  hosts: local
  roles:
    - dotfiles
    - tools.common
    - tools.py
    - tools.atuin
    - tools.noti
    - tools.starship
    - tools.vale
    - tools.helm
    - tools.k9s
    - tools.flux
    - tools.kubectl
    - tools.glab
    - tools.skaffold
    - tools.terraform
