---
- name: Bootstrap local env
  hosts: local
  roles:
    - dotfiles
    - tools.common
    - tools.py
    - tools.atuin
    - tools.noti
    - tools.starship
    - tools.vale
    - tools.helm
    - tools.k9s
    - tools.flux
    - tools.kubectl
    # TODO:
    # - tools.tfenv
    # - tools.terraform
    # - tools.glab
    # - tools.skaffold
