---
- name: Bootstrap local env
  hosts: local
  vars:
    gh_auth: true
  roles:
    - dotfiles
    - tools.common
    - tools.vars
    # TODO: remove tools.py in the future after all hosts have been migrated to tools.uv
    - tools.py
    - tools.atuin
    - tools.direnv
    - tools.noti
    - tools.osv-scanner
    - tools.sops
    - tools.starship
    - tools.uv
    - tools.vale
    # work
    - tools.dive
    - tools.docker-plugins
    - tools.flux
    - tools.glab
    - tools.hadolint
    - tools.helm
    - tools.helm-docs
    - tools.k9s
    - tools.kubectl
    - tools.kubeconform
    - tools.kustomize
    - tools.skaffold
    - tools.terraform
    # other
    - tools.gh
