---
- name: Bootstrap local env
  hosts: local
  roles:
    - dotfiles
    - tools.common
    - tools.py
    - tools.atuin
    - tools.noti
    - tools.osv-scanner
    - tools.sops
    - tools.starship
    - tools.vale
    # work
    - tools.docker-plugins
    - tools.flux
    - tools.glab
    - tools.helm
    - tools.helm-docs
    - tools.k9s
    - tools.kubectl
    - tools.kubeconform
    - tools.skaffold
    - tools.terraform
    # other
    - tools.gh
